#!/usr/bin/env python3
"""Extracts ZiNc's original key->bit tables from controller.znc and emits tables.h.
Every entry is tagged with a logical role so the new plugin can remap it."""
import struct, sys
d = open(sys.argv[1] if len(sys.argv) > 1 else '../controller.znc', 'rb').read()
rd = lambda va, n: d[va - 0x10000000: va - 0x10000000 + n]
ROLES = ['up', 'down', 'left', 'right', 'b1', 'b2', 'b3', 'b4', 'b5', 'b6', 'start']
P = [  # original DirectInput scancodes per player
    {0xc8: 'up', 0xd0: 'down', 0xcb: 'left', 0xcd: 'right', 0x1e: 'b1', 0x1f: 'b2', 0x20: 'b3',
     0x2c: 'b4', 0x2d: 'b5', 0x2e: 'b6', 0x02: 'start'},
    {0x23: 'up', 0x31: 'down', 0x30: 'left', 0x32: 'right', 0x24: 'b1', 0x25: 'b2', 0x26: 'b3',
     0x16: 'b4', 0x17: 'b5', 0x18: 'b6', 0x03: 'start'}]
SYS = {0x06: 'coin1', 0x07: 'coin2', 0x05: 'test', 0x08: 'service'}
SYSNAMES = ['coin1', 'coin2', 'test', 'service']
role_id = lambda p, r: p * 11 + ROLES.index(r)
sys_id = lambda s: 22 + SYSNAMES.index(s)
DIK2VK = {0x13: 0x52, 0x10: 0x51, 0x11: 0x57, 0x12: 0x45, 0x21: 0x46, 0x24: 0x4A, 0x25: 0x4B, 0x26: 0x4C}
tableaddr = [0x1000b658, 0x1000b040, 0x1000b248, 0x1000b450]
typemap = list(rd(0x100012cd, 16))
out = ['/* generated by gen_tables.py from the original controller.znc - do not edit */',
       'typedef struct { unsigned char out, bit, vk; short role; } Ent;']
for t, a in enumerate(tableaddr):
    n = struct.unpack('<I', rd(a, 4))[0]
    ents = []
    for p in range(4):
        for i in range(n):
            k, b = struct.unpack('<II', rd(a + 4 + 0x80 * p + 8 * i, 8))
            if k == 0 and b == 0:
                continue
            if k in SYS:
                ents.append((p + 1, b, 0, sys_id(SYS[k])))
            elif p < 2 and k in P[p]:
                ents.append((p + 1, b, 0, role_id(p, P[p][k])))
            elif p == 0 and k in DIK2VK:
                ents.append((1, b, DIK2VK[k], -1))   # extra button, stays on its letter key
            # anything else is a placeholder entry for players that do not exist: dropped
    out.append(f'static const Ent T{t}[] = {{')
    out += [f'  {{{o},{b},0x{vk:02X},{r}}},' for o, b, vk, r in ents]
    out.append('};')
out.append('static const struct { const Ent *e; int n; } TABLES[5] = { ' +
           ', '.join(f'{{T{t},(int)(sizeof T{t}/sizeof T{t}[0])}}' for t in range(4)) + ', {0,0} };')
out.append('static const unsigned char TYPEMAP[16] = {' + ','.join(map(str, typemap)) + '};')
out.append('static const unsigned long SYSMASK[4] = {0x10,0x20,0x1,0x2}; /* coin1,coin2,test,service -> out[0] */')
open('tables.h', 'w').write('\n'.join(out) + '\n')
print('\n'.join(out[:12]), '...')
