/* Generated from the SFEX2 Plus FAQ moves lists (input-plugin/presets/gen_presets.py). DO NOT EDIT. */
#include "common.h"

static const ComboMove moves0[] = {
    {"Throw", "Transmission", "4+MP", "When close, b / f + MP / HP"},
    {"Throw", "O.C.R.", "4+MK", "When close, b / f + MK / HK"},
    {"Guard Break", "Hard Crash", "HP+HK", "Press the same strength P + K"},
    {"Special", "Humming Rush", "236+HP", "qcf + P"},
    {"Special", "Terminator", "421+HP", "b,d,db + P"},
    {"Special", "Alternative Catch", "63214+HK", "hcb + K"},
    {"Special", "Jackson Kick", "236+HK", "qcf + K"},
    {"Special", "Cancer Crash", "LP LP 6 LK HP", "LP,LP,f,LK,HP"},
    {"Special", "Shift Stamp Punch", "3+MP", "df + MP"},
    {"Special", "Shift Club Upper", "3+HP", "df + HP"},
    {"Special", "Shift Club Straight", "6+HP", "f + HP"},
    {"Special", "Job Step", "6+MK", "f + MK"},
    {"Special", "Pulldown Leg", "6+HK", "f + HK"},
    {"Super", "Great Cancer", "236236+HP", "qcf,qcf + P  (hold P to delay)"},
    {"Super", "Five Star Raid", "236236+HK", "qcf,qcf + K"},
    {"Meteor", "Final Cancer", "214214+LP+MP+HP", "qcb,qcb + PPP"},
};
static const ComboMove moves1[] = {
    {"Throw", "Wire Smash", "4+MP", "When close, b / f + MP / HP"},
    {"Guard Break", "Tureno Claw", "HP+HK", "Press the same strength P + K"},
    {"Special", "Rolling Crystal Flash", "1*C 6+HP", "Charge b,f + P"},
    {"Special", "Sky High Claw", "1*C 8 8+HP", "Charge d,ub~uf + P"},
    {"Special", "Advancing Wire", "1*C 8 8+HK", "Charge d,ub~uf + K, move b / f..."},
    {"Special", "Attaching Claw", "623+HP", "f,d,df + P"},
    {"Special", "Backslash", "LK+MK+HK", "Press KKK"},
    {"Super", "Ground Crystal Flash", "1*C 646+HP", "Charge b,f,b,f + P"},
    {"Super", "Scarlet Terror", "1*C 646+HK", "Charge b,f,b,f + K"},
    {"Super", "Sky High Illusion", "1*C 318 8+HP", "Charge db,df,db,ub~uf + P"},
    {"Meteor", "Advancing Wire SP", "1*C 318 8+HK", "Charge db,df,db,ub~uf + K, move b / f..."},
};
static const ComboMove moves2[] = {
    {"Throw", "Wild Fang", "4+HP", "When close, b / f + HP"},
    {"Guard Break", "Raging Nail", "HP+HK", "Press the same strength P + K"},
    {"Special", "Vertical Rolling", "1*C 8 8+HK", "Charge d,u + K"},
    {"Special", "Rolling Attack", "1*C 6+HP", "Charge b,f + P"},
    {"Special", "Backstep Rolling", "1*C 6+HK", "Charge b,f + K (press P to abort)"},
    {"Special", "Surprise Forward", "LK+MK+HK", "Press KKK"},
    {"Special", "Amazon River Run", "3+HP", "df + HP"},
    {"Special", "Rock Crush", "6+MP", "f + MP"},
    {"Super", "Ground Shave Rolling", "1*C 646+HP", "Charge b,f,b,f + P  (hold P to delay)"},
    {"Super", "Jungle Beat", "1*C 646+HK", "Charge b,f,b,f + K"},
    {"Meteor", "Super Electric Thunder", "236236+LK+MK+HK", "qcf,qcf + KKK"},
};
static const ComboMove moves3[] = {
    {"Throw", "Koshuu Da (Attacking Tiger Strike)", "4+MP", "When close, b / f + MP / HP"},
    {"Throw", "Koshuu Raku (Attacking Tiger Drop)", "4+MK", "When close, b / f + MK / HK"},
    {"Guard Break", "Sen'en Shuu (Spinning Circle Kick)", "HP+HK", "Press the same strength P + K"},
    {"Special", "Gomen ne! (\"I'm sorry!\")", "LP LP 6 LK HP", "LP,LP,f,LK,HP"},
    {"Special", "Kaiten-teki Kaku Kyakushuu (Rotary Target Crane Leg Kick  (a.k.a. 'Spinning Bird Kick'))", "236+HK", "qcf + K"},
    {"Special", "Hien Shuu (Flying Kick)", "214+HK", "qcb + K"},
    {"Special", "Sou Shouda (Paired Palm Strike)", "6+MP", "f + MP"},
    {"Super", "Kikou Shou (Chi (Internal Energy) Palm)", "236236+HP", "qcf,qcf + P"},
    {"Super", "Senretsu Kyaku (Thousand Rending Kicks)", "236236+HK", "qcf,qcf + K"},
    {"Super", "Hazan Tenshou Kyaku (Supreme Mountain Ascension Kick)", "214214+HK", "qcb,qcb + K"},
    {"Meteor", "Kikou Shou: Goku (Ultimate Chi Palm)", "236236+LP+MP+HP", "qcf,qcf + PPP"},
};
static const ComboMove moves4[] = {
    {"Throw", "Power Hunter", "4+MP", "When close, b / f + MP / HP"},
    {"Throw", "Power Lift Throw", "4+MK", "When close, b / f + MK / HK"},
    {"Guard Break", "Double Arm Punch", "HP+HK", "Press the same strength P + K"},
    {"Special", "Dash Straight", "1*C 6+HP", "Charge b,f + P"},
    {"Special", "Dash Upper", "1*C 6+HK", "Charge b,f + K"},
    {"Special", "Feint Dash", "214+HP", "qcb + P"},
    {"Special", "Batting Hero", "41236+HP", "hcf + P"},
    {"Special", "Soccer Ball Kick", "41236+HK", "hcf + K"},
    {"Special", "Angry Fist", "6+MP", "f + MP"},
    {"Super", "Crazy Jack", "1*C 646+HP", "Charge b,f,b,f + P  (press K, then P)"},
    {"Super", "Raging Buffalo", "1*C 646+HK", "Charge b,f,b,f + K"},
    {"Super", "Home Run Hero", "214214+HP", "qcb,qcb + P"},
    {"Super", "Grand Slam Crusher", "214214+HK", "qcb,qcb + K"},
    {"Meteor", "Home Run King", "236236+LK+MK+HK", "qcf,qcf + KKK  (can then press P)"},
};
static const ComboMove moves5[] = {
    {"Throw", "Backdrop", "4+MP", "When close, b / f + MP / HP"},
    {"Throw", "German Suplex", "4+MK", "When close, b / f + MK / HK"},
    {"Guard Break", "Ganges Chop", "HP+HK", "Press the same strength P + K"},
    {"Special", "Lariat", "236+HP", "qcf + P"},
    {"Special", "Darun Catch", "421+HP", "b,d,db + P"},
    {"Special", "Ganges DDT", "623+HK", "f,d,df + K"},
    {"Special", "Brahma Bomb", "632147+HP", "Rotate 360 + P  (misses from afar)"},
    {"Special", "Indra Bashi (Indra Bridge)", "632147+HK", "Rotate 360 + K  (misses from afar)"},
    {"Special", "Daikaku (Omnipotence)", "LP+MP+HP", "Press PPP"},
    {"Super", "Indra~ Bashi (\"Indraa--!\" Bridge)", "214214+HK", "qcb,qcb + K"},
    {"Super", "Chouzetsu Kishin Bomb (Superior Terrible God Bomb)", "632147632147+HP", "Rotate 720 + P  (misses from afar)"},
    {"Meteor", "G.O.D.", "632147+LP+MP+HP", "Rotate 360 + PPP (misses from afar)"},
};
static const ComboMove moves6[] = {
    {"Throw", "Yoga Smash", "4+MP", "When close, b / f + MP / HP"},
    {"Throw", "Yoga Throw", "4+MK", "When close, b / f + MK / HK"},
    {"Guard Break", "Yoga Shock", "HP+HK", "Press the same strength P + K"},
    {"Special", "Yoga Fire", "236+HP", "qcf + P"},
    {"Special", "Yoga Flame", "214+HP", "qcb + P"},
    {"Special", "Yoga Blast", "214+HK", "qcb + K"},
    {"Special", "Yoga Catch", "236+HK", "qcf + K"},
    {"Special", "Yoga Teleport (Zen Idou) (Yoga Teleport (Move Forward))", "623+LP+MP+HP", "f,d,df + PPP / KKK"},
    {"Special", "Yoga Teleport (Go Idou) (Yoga Teleport (Move Backward))", "421+LP+MP+HP", "b,d,db + PPP / KKK"},
    {"Special", "Kuuchuu Fuyuu (Float in Mid-Air)", "69874+HK", "f,uf,u,ub,b + K  (air)"},
    {"Super", "Yoga Legend", "214214+HK", "qcb,qcb + K"},
    {"Meteor", "Yoga Inferno", "236236+LP+MP+HP", "qcf,qcf + PPP"},
};
static const ComboMove moves7[] = {
    {"Throw", "DEATH Moment", "4+MP", "When close, b / f + MP / HP"},
    {"Throw", "DARK Throw", "4+MK", "When close, b / f + MK / HK"},
    {"Guard Break", "SHUDDER Blade", "HP+HK", "Press the same strength P + K"},
    {"Special", "KILL Wire", "623+HP", "f,d,df + P"},
    {"Special", "DARK Wire", "236+HP", "qcf + P"},
    {"Special", "EX-plosive", "236+HK", "qcf + K"},
    {"Special", "KNIFE Nightmare", "6+MP", "f + MP"},
    {"Special", "DEATH Spin Kick", "6+MK", "f + MK"},
    {"Super", "KILL Trump", "23623+HP", "qcf,d,df + P"},
    {"Super", "DARK Shackle", "23623+HK", "qcf,d,df + K"},
    {"Super", "EX-Prominence", "214214+HK", "qcb,qcb + K"},
    {"Meteor", "DEATH Trap", "214214+LP+MP+HP", "qcb,qcb + PPP"},
};
static const ComboMove moves8[] = {
    {"Throw", "Judo Throw", "4+MP", "When close, b / f + MP / HP"},
    {"Throw", "Dragon Suplex", "4+MK", "When close, b / f + MK / HK"},
    {"Guard Break", "Elbow Stamp", "HP+HK", "Press the same strength P + K"},
    {"Special", "Sonic Boom", "1*C 6+HP", "Charge b,f + P"},
    {"Special", "Somersault Kick", "1*C 8 8+HK", "Charge d,u + K"},
    {"Special", "Heavy Stab Kick", "4+HK", "b / f + HK"},
    {"Special", "Rolling Sobat", "4+MK", "b / f + MK"},
    {"Special", "Spinning Back Knuckle", "6+HP", "f + HP"},
    {"Super", "Double Somersault Kick", "1*C 319 9+HK", "Charge db,df,db,uf + K"},
    {"Super", "Opening Gambit", "1*C 646+HP", "Charge b,f,b,f + P"},
    {"Meteor", "Sonic Boom Typhoon", "1*C 646+LK+MK+HK", "Charge b,f,b,f + KKK"},
};
static const ComboMove moves9[] = {
    {"Throw", "Kyaku (Capture)", "4+MP", "When close, b / f + MP / HP"},
    {"Throw", "Keishukou (\"Strangle neck with one's hands\")", "4+MK", "When close, b / f + MK / HK"},
    {"Guard Break", "Bukyaku Zan (Dancing Slash Attack)", "HP+HK", "Press the same strength P + K"},
    {"Special", "Chuugeki Hou (Demolishing Elbow Attack)", "236+HP", "qcf + P"},
    {"Special", "Shinkuu Geki (Shaking Air Attack)", "214+HP", "qcb + P  (or b + P from Chuugeki Hou)"},
    {"Special", "Shinkyaku Geki (Shaking Leg Attack)", "214+HK", "qcb + K  (or b + K from Chuugeki Hou)"},
    {"Special", "Ryuusui (Stream)", "632147+HP", "When close, rotate 360 + P"},
    {"Special", "Gokyaku Kou (Defend Into Attack)", "421+HP", "b,d,db + P"},
    {"Special", "Chuuhou (Demolishing Elbow)", "6+HP", "f + HP"},
    {"Special", "Kaishuu (Reaping Kick)", "6+HK", "f + HK"},
    {"Super", "Renbu (Rapid Dance)", "LP LP 6 LK HP", "LP,LP,f,LK,HP"},
    {"Super", "Kiren'eki (Refined Spirit Shoot)", "214214+HP", "qcb,qcb + P, hold P to delay"},
    {"Super", "Kyaku Hougi (Attacking Phoenix Technique)", "214214+HK", "qcb,qcb + K"},
    {"Super", "Renshou Geki (Violent Rapid Rise)", "236236+HP", "qcf,qcf + P"},
    {"Meteor", "Shirase Gatana (Obituary Sword)", "236236+LK+MK+HK", "qcf,qcf + KKK"},
};
static const ComboMove moves10[] = {
    {"Throw", "Seoi Nage (Over The Shoulder Throw)", "4+MP", "When close, b / f + MP / HP"},
    {"Throw", "Jigoku Guruma (Hell Wheel)", "4+MK", "When close, b / f + MK / HK"},
    {"Guard Break", "Inazuma Kakato Wari (Lightning Flash Splitting Heel)", "HP+HK", "Press the same strength P + K"},
    {"Special", "Hadou Ken (Surge Fist)", "236+HP", "qcf + P"},
    {"Special", "Shouryuu Ken (Rising Dragon Fist)", "623+HP", "f,d,df + P"},
    {"Special", "Tatsumaki Senpuu Kyaku (Tornado Whirlwind Kick)", "214+HK", "qcb + K"},
    {"Special", "Zenpou Tenshin (Forward Body Roll)", "214+HP", "qcb + P"},
    {"Super", "Shouryuu Reppa (Rising Dragon Render)", "23623+HP", "qcf,d,df + P"},
    {"Super", "Shinryuu Ken (Divine Dragon Fist)", "23623+HK", "qcf,d,df + K, tap P / K / dir. rapidly"},
    {"Super", "Shippuujinrai Kyaku (\"Swift as Lightning\" Kick)", "214214+HK", "qcb,qcb + K"},
    {"Meteor", "Kuzuryuu Reppa (Nine-Headed Dragon Render)", "214214+LK+MK+HK", "qcb,qcb + KKK, tap P / K / dir. rapidly"},
};
static const ComboMove moves11[] = {
    {"Throw", "Kyaku (Capture)", "4+MP", "When close, b / f + MP / HP"},
    {"Throw", "Keishukou (\"Strangle neck with one's hands\")", "4+MK", "When close, b / f + MK / HK"},
    {"Special", "Sanren Kon (Three Rapid Canes)", "236+HP", "qcf + P  (then input f + P two times)"},
    {"Special", "Tenshou Kon (Ascention Cane)", "623+HP", "f,d,df + P  (or u + P after Sanren Kon)"},
    {"Special", "Gekkyou Botan (Moon-Mirror Tree Peony)", "421+HP", "b,d,db + P, then hold P"},
    {"Special", "Kasumi Oroshi (Misty Mountain Wind)", "214+HK", "qcb + K, then K,K  (or during Sanren Kon)"},
    {"Special", "Ryuusui (Stream)", "632147+HP", "When close, rotate 360 + P"},
    {"Special", "Tou Chuuhou (Demolishing Elbow Step)", "6+MP", "f + MP"},
    {"Super", "Izayoi Rekkon (Sixteen-Day Old Moon: Violent Cane)", "236236+HP", "qcf,qcf + P"},
    {"Super", "Yayoi Toukon Gi (Month of March: Cane Throwing Technique)", "214214+HP", "qcb,qcb + P  (air)"},
    {"Meteor", "Machiyoi Tenkyuu Geki (\"Violent rain from a cloudy sky, in the early morning\")", "LP LP 6 LK HP", "LP,LP,f,LK,HP"},
};
static const ComboMove moves12[] = {
    {"Throw", "Ordence Foot", "4+MP", "When close, b / f + MP / HP"},
    {"Throw", "Neck Factor", "4+MK", "When close, b / f + MK / HK"},
    {"Guard Break", "Arakul Ankle", "HP+HK", "Press the same strength P + K"},
    {"Special", "Drill Purrus (Chijou) (Ground Drill Purrus)", "236+HK", "qcf + K"},
    {"Special", "Ten'el Kick", "214+HK", "qcb + K"},
    {"Special", "Prim Kick", "623+HK", "f,d,df + K"},
    {"Special", "Arakul Wrist", "6+MP", "f + MP"},
    {"Super", "Reswal Kahna", "236236+HK", "qcf,qcf + K"},
    {"Super", "Praec Larm", "214214+HK", "qcb,qcb + K"},
    {"Meteor", "Gradeus Pearl", "236236+LP+MP+HP", "qcf,qcf + PPP"},
};
static const ComboMove moves13[] = {
    {"Throw", "Seoi Nage (Over The Shoulder Throw)", "4+MP", "When close, b / f + MP / HP"},
    {"Throw", "Tomoe Nage ((A judo technique) Throw)", "4+MK", "When close, b / f + MK / HK"},
    {"Guard Break", "Sakotsu Wari (Collarbone Splitter)", "HP+HK", "Press the same strength P + K"},
    {"Special", "Hadou Ken (Surge Fist)", "236+HP", "qcf + P"},
    {"Special", "Shakunetsu Hadou Ken (Scorching Heat Surge fist)", "63214+HP", "hcb + P"},
    {"Special", "Shouryuu Ken (Rising Dragon Fist)", "623+HP", "f,d,df + P"},
    {"Special", "Tatsumaki Senpuu Kyaku (Tornado Whirlwind Kick)", "214+HK", "qcb + K (then b + K x2, then/or press K)"},
    {"Special", "Kyuubi Kudaki (Dove's Tail Crusher)", "6+HP", "f + HP"},
    {"Special", "Senpuu Kyaku (Whirlwind Kick)", "6+MK", "f + MK"},
    {"Super", "Shinkuu Hadou Ken (Vacuum Surge Fist)", "236236+HP", "qcf,qcf + P"},
    {"Super", "Shinkuu Tatsumaki Senpuu Kyaku (Vacuum Tornado Whirlwind Kick)", "214214+HK", "qcb,qcb + K"},
    {"Meteor", "Shin Shouryuu Ken (True Rising Dragon Fist)", "236236+LK+MK+HK", "qcf,qcf + KKK"},
};
static const ComboMove moves14[] = {
    {"Throw", "Tiger Carry", "4+MP", "When close, b / f + MP / HP"},
    {"Throw", "Tiger Rage", "4+MK", "When close, b / f + MK / HK"},
    {"Guard Break", "Tiger Tool", "HP+HK", "Press the same strength P + K"},
    {"Special", "Tiger Shot", "236+HP", "qcf + P"},
    {"Special", "Ground Tiger Shot", "236+HK", "qcf + K"},
    {"Special", "Tiger Fake", "421+HP", "b,d,db + P"},
    {"Special", "Tiger Blow", "623+HP", "f,d,df + P"},
    {"Special", "Tiger Crush", "623+HK", "f,d,df + K"},
    {"Super", "Tiger Genocide", "214214+HP", "qcb,qcb + P"},
    {"Super", "Tiger Raid", "214214+HK", "qcb,qcb + K"},
    {"Super", "Tiger Cannon", "236236+HP", "qcf,qcf + P"},
    {"Super", "Ground Tiger Cannon", "236236+HK", "qcf,qcf + K"},
    {"Meteor", "Tiger Storm", "236236+LP+MP+HP", "qcf,qcf + PPP  (press P up to 5 times)"},
};
static const ComboMove moves15[] = {
    {"Throw", "Bloody Mount", "4+MP", "When close, b / f + MP / HP"},
    {"Throw", "Bloody Choke", "4+MK", "When close, b / f + MK / HK"},
    {"Guard Break", "Spinning Double Knuckle", "HP+HK", "Press the same strength P + K"},
    {"Special", "Gale Hammer Punch", "236+HP", "qcf + P"},
    {"Special", "Bermuda Symphony", "623+HK", "f,d,df + K  (df + K from G. Hammer Punch)"},
    {"Special", "Half Moon Kick", "214+HK", "qcb + K  (ub~db from Gale Hammer Punch)"},
    {"Special", "Crimson Terror", "632147+HP", "When close, rotate 360 + P"},
    {"Special", "Sliding Sweeper", "3+HK", "df + HK"},
    {"Special", "Crash Punch", "6+HP", "f + HP"},
    {"Special", "Step Combo Punch", "6+MP", "f + MP"},
    {"Special", "Step Combo Kick", "6+MK", "f + MK"},
    {"Super", "Load", "236236+HP", "qcf,qcf + P"},
    {"Super", "Shuttle Combination", "214214+HP", "qcb,qcb + P"},
    {"Super", "Sharon Special", "236236+HK", "qcf,qcf + K"},
    {"Meteor", "Assault Rifle", "236236+LP+MP+HP", "qcf,qcf + PPP  (changes from up close)"},
};
static const ComboMove moves16[] = {
    {"Throw", "Skullo Stand", "4+MP", "When close, b / f + MP / HP"},
    {"Guard Break", "Skullo Punch", "HP+HK", "Press the same strength P + K"},
    {"Special", "Skullo Crusher", "236+HP", "qcf + P"},
    {"Special", "Skullo Slider", "236+HK", "qcf + K"},
    {"Special", "Skullo Head", "623+HP", "f,d,df + P"},
    {"Special", "Skullo Shock", "6321478+HP", "hcb,ub,u + P"},
    {"Special", "Skullo T'katchev", "421+HK", "b,d,db + K"},
    {"Special", "Skullo Back Ten (Skullo Backspin)", "4 ~ 4", "Tap b,b"},
    {"Special", "Skullo Dash", "6 ~ 6", "Tap f,f"},
    {"Special", "Stepping Upper", "6+MP", "f + MP"},
    {"Special", "Dangerous Heel", "6+MK", "f + MK"},
    {"Super", "Shin Skullo Dream (New Skullo Dream)", "LP LP 6 LK HP", "LP,LP,f,LK,HP"},
    {"Super", "Super Skullo Crusher", "236236+HP", "qcf,qcf + P"},
    {"Super", "Super Skullo Slider", "236236+HK", "qcf,qcf + K"},
    {"Super", "Skullo Ball", "214214+HP", "qcb,qcb + P  (can perform 2 times)"},
    {"Super", "Skullo Energy", "214214+HK", "qcb,qcb + K"},
    {"Meteor", "Super Skullo Energy", "214214+LK+MK+HK", "qcb,qcb + KKK"},
};
static const ComboMove moves17[] = {
    {"Throw", "Deadly Throw", "4+MP", "When close, b / f + MP / HP"},
    {"Throw", "Death Suplex", "4+MK", "When close, b / f + MK / HK"},
    {"Guard Break", "Psychic Crush", "HP+HK", "Press the same strength P + K"},
    {"Special", "Psycho Crusher", "1*C 6+HP", "Charge b,f + P"},
    {"Special", "Double Knee Press", "1*C 6+HK", "Charge b,f + K"},
    {"Special", "Head Press", "1*C 8 8+HP", "Charge d,u + P, move b / f afterwards"},
    {"Special", "Vega Warp (Zenpou Idou)", "623+LP+MP+HP", "f,d,df + PPP / KKK"},
    {"Special", "Vega Warp (Kouhou Idou)", "421+LP+MP+HP", "b,d,db + PPP / KKK"},
    {"Super", "Psycho Cannon", "1*C 646+HP", "Charge b,f,b,f + P  (hold P to delay)"},
    {"Super", "Knee Press Nightmare", "1*C 646+HK", "Charge b,f,b,f + K"},
    {"Meteor", "Psycho Break Smasher", "1*C 646+LP+MP+HP", "Charge b,f,b,f + PPP"},
};
static const ComboMove moves18[] = {
    {"Throw", "Digestiveo", "4+MP", "When close, b / f + MP / HP"},
    {"Guard Break", "Respresso", "HP+HK", "Press the same strength P + K"},
    {"Special", "Volcanus", "214+HP", "qcb + P"},
    {"Special", "Cannosa no Kutsujoku", "214+HK", "qcb + K  (counters attacks)"},
    {"Special", "Hibashiri (Running Fire)", "236+HK", "qcf + K"},
    {"Special", "Vesuvio no Ikari (Vesuvius' Anger  (Vesuvius is a volcano in Italy))", "236+HP", "qcf + P"},
    {"Special", "Io no Yoku (Wings of Io  (Io is a volcanic Jovian moon))", "LP+MP+HP", "Press (b / f +) PPP"},
    {"Super", "Tameiki no Hashi (Bridge's Sigh)", "236236+HP", "qcf,qcf + P"},
    {"Super", "Accelerando", "214214+HK", "qcb,qcb + K"},
    {"Super", "Pisa no Shatou (Leaning Tower of Pisa)", "21421+HP", "qcb,d,db + P"},
    {"Meteor", "Shikei (Four Scenes)", "236236+LK+MK+HK", "qcf,qcf + KKK  (misses from afar)"},
};
static const ComboMove moves19[] = {
    {"Throw", "Iron Claw", "4+MP", "When close, b / f + MP / HP"},
    {"Throw", "German Suplex", "4+MK", "When close, b / f + MK / HK"},
    {"Guard Break", "Russian Headbutt", "HP+HK", "Press the same strength P + K"},
    {"Special", "Double Lariat", "4+LP+MP+HP", "b / f + PPP, or press PPP, move b / f"},
    {"Special", "Quick Double Lariat", "4+LK+MK+HK", "b / f + KKK, or press KKK, move b / f"},
    {"Special", "Spinning Piledriver", "632147+HP", "Rotate 360 + P  (misses from afar)"},
    {"Special", "Atomic Suplex", "632147+HK", "When close, rotate 360 + K"},
    {"Super", "Final Atomic Buster", "632147632147+HP", "Rotate 720 + P  (misses from afar)"},
    {"Super", "Aerial Russian Slam", "214214+HK", "qcb,qcb + K"},
    {"Super", "Super Stomping", "236236+HK", "qcf,qcf + K"},
    {"Meteor", "Cosmic Final Atomic Buster", "632147632147+LP+MP+HP", "Rotate 720 + PPP  (misses from afar)"},
};
static const ComboMove moves20[] = {
    {"Throw", "Satsuga (Deadly Fang)", "4+MP", "When close, b / f + MP / HP"},
    {"Throw", "Shouki (Soaring Devil)", "4+MK", "When close, b / f + MK / HK"},
    {"Guard Break", "Saiga (Smashing Fang)", "HP+HK", "Press the same strength P + K"},
    {"Special", "Shuuga (Attacking Fang)", "236+HP", "qcf + P"},
    {"Special", "Gouga (Roaring Fang)", "41236+HK", "hcf + K"},
    {"Special", "Jazan (Serpent Slash)", "421+HP", "b,d,db + P"},
    {"Special", "Kizan (Devil Slash)", "623+HP", "f,d,df + P"},
    {"Special", "Raiga (Lightning Fang)", "623+HK", "f,d,df + K"},
    {"Special", "Bu (Dance)", "623+LP+MP+HP", "f,d,df + PPP, then press P to stop"},
    {"Special", "Zanki (Murderous Devil)", "6+HP", "f + HP"},
    {"Special", "Kyouja (Insane Serpent)", "6+HK", "f + HK"},
    {"Super", "Kienshou (Demonic Swallow Flight)", "236236+HP", "qcf,qcf + P, tap P / K / dir. rapidly"},
    {"Super", "Kienbu (Demonic Swallow Dance)", "214214+HP", "qcb,qcb + P  (air)"},
    {"Super", "Soukondan (Spirits of the Dead Bullet)", "214214+HK", "qcb,qcb + K  (hold K to delay)"},
    {"Meteor", "Kyoujin Senshuu (Evil Spinning Blade Attack)", "214214+LK+MK+HK", "qcb,qcb + KKK  (then use D. Rasen Shou)"},
    {"Meteor", "Daikyo Rasen Shou (Great Untruth Spiral Flight)", "236236+HK", "qcf,qcf + K, tap P / K / dir. rapidly"},
};
static const ComboMove moves21[] = {
    {"Throw", "Madomashi (Beguiling (?))", "4+MP", "When close, b / f + MP / HP"},
    {"Guard Break", "Daigatana (Great Sword)", "HP+HK", "Press the same strength P + K"},
    {"Special", "Kamaitachi (Whirlwind Cut)", "236+HP", "qcf + P"},
    {"Special", "Oborodzuki (Hazy Moon)", "236+HK", "qcf + K"},
    {"Special", "Hisen Zan (Flying Spin Slash)", "623+HP", "f,d,df + P"},
    {"Special", "Shiraha Tenjin (Clashing Blade Sword Turn)", "421+HP", "b,d,db + P"},
    {"Special", "Enraku Shishou (Swallow-Slaying Violet Rise)", "6+HP", "f + HP"},
    {"Super", "Resshin Kamaitachi (Disastrous Earthquake Whirlwind Cut)", "236236+HP", "qcf,qcf + P"},
    {"Super", "Raizanshou (Flying Lightning Slash)", "23623+HK", "qcf,d,df + K, tap P / K / dir. rapidly"},
    {"Meteor", "Orochi Fuujin (Taichi) (Great Serpent Sealing Blade (Anti-Ground))", "214214+LP+MP+HP", "qcb,qcb + PPP to counter ground attacks"},
    {"Meteor", "Orochi Fuujin (Taikuu) (Great Serpent Sealing Blade (Anti-Air))", "214214+LP+MP+HP", "qcb,qcb + PPP to counter aerial attacks"},
};
static const ComboMove moves22[] = {
    {"Throw", "Kutei Kaku (Arm Strike Hold)", "4+MP", "When close, b / f + MP / HP"},
    {"Throw", "Ura Jigoku Guruma (Reverse Hell Wheel)", "4+MK", "When close, b / f + MK / HK"},
    {"Guard Break", "Bukyaku (Warrior Kick)", "HP+HK", "Press the same strength P + K"},
    {"Special", "Shinki Hatsudou (Divine Soul Invocation)", "236+HP", "qcf + P"},
    {"Special", "Mouryou Kasen (Nature Spirits' Whirling Vortex)", "214+HK", "qcb + K (then b + K x2, then/or press K)"},
    {"Special", "Maryuu Rekkou (Evil Dragon Destroying Light)", "623+HP", "f,d,df + P"},
    {"Special", "Makuu Shihai (Zenpou Idou)", "623+LP+MP+HP", "f,d,df + PPP / KKK"},
    {"Special", "Makuu Shihai (Kouhou Idou)", "421+LP+MP+HP", "b,d,db + PPP / KKK"},
    {"Special", "Ryuubu (Dragon Warrior)", "6+MK", "f + MK"},
    {"Super", "Sairou Kyoushuu", "214214+HP", "qcb,qcb + P"},
    {"Meteor", "Shouki Hatsudou (Demonic Disease Invocation)", "236236+LP+MP+HP", "qcf,qcf + PPP"},
    {"Meteor", "Kyouja Renbu (Villainous Rapid Dance)", "LP LP 6 LK HP", "LP,LP,f,LK,HP"},
};
static const ComboMove moves23[] = {
    {"Throw", "Death Stand", "4+MP", "When close, b / f + MP / HP"},
    {"Guard Break", "Death Kick", "HP+HK", "Press the same strength P + K"},
    {"Special", "Death Crusher", "236+HP", "qcf + P"},
    {"Special", "Death Break", "236+HK", "qcf + K"},
    {"Special", "Death Shock", "6321478+HP", "hcb,ub,u + P"},
    {"Special", "Death Press", "421+HK", "b,d,db + K"},
    {"Special", "Death Escape", "4 ~ 4", "Tap b,b"},
    {"Special", "Stepping Upper", "6+MP", "f + MP"},
    {"Special", "Death Heel", "6+MK", "f + MK"},
    {"Super", "Death Dream (Chijou) (Ground Death Dream)", "LP LP 6 LK HP", "LP,LP,f,LK,HP"},
    {"Super", "Death Government", "236236+HP", "qcf,qcf + P"},
    {"Super", "Death Crusher", "236236+HK", "qcf,qcf + K"},
    {"Super", "Death Energy", "214214+HP", "qcb,qcb + P"},
    {"Meteor", "Super Death Energy", "214214+LP+MP+HP", "qcb,qcb + PPP"},
};
static const ComboMove moves24[] = {
    {"Throw", "Deadly Throw", "4+MP", "When close, b / f + MP / HP"},
    {"Throw", "Death Suplex", "4+MK", "When close, b / f + MK / HK"},
    {"Guard Break", "Psychic Crush", "HP+HK", "Press the same strength P + K"},
    {"Special", "Psycho Crusher", "1*C 6+HP", "Charge b,f + P"},
    {"Special", "Double Knee Press", "1*C 6+HK", "Charge b,f + K"},
    {"Special", "Head Press", "1*C 8 8+HP", "Charge d,u + P, move b / f afterwards"},
    {"Special", "Vega Warp (Zenpou Idou)", "623+LP+MP+HP", "f,d,df + PPP / KKK"},
    {"Special", "Vega Warp (Kouhou Idou)", "421+LP+MP+HP", "b,d,db + PPP / KKK"},
    {"Super", "Psycho Cannon G", "236236+HP", "qcf,qcf + P  (hold P to delay)"},
    {"Super", "Psycho Cannon B", "214214+HP", "qcb,qcb + P / K  (hold P to delay)"},
    {"Super", "Psycho Cannon R", "1*C 646+HP", "Charge b,f,b,f + P  (hold P to delay)"},
    {"Super", "Knee Press Nightmare", "1*C 646+HK", "Charge b,f,b,f + K"},
    {"Meteor", "Psycho Break Smasher", "1*C 646+LP+MP+HP", "Charge b,f,b,f + PPP"},
};
const ComboChar g_comboChars[] = {
    {"Area", moves0, 16},
    {"Balrog (Vega in the West)", moves1, 11},
    {"Blanka", moves2, 11},
    {"Chun-Li", moves3, 11},
    {"Cracker Jack", moves4, 14},
    {"Darun Mister", moves5, 12},
    {"Dhalsim", moves6, 12},
    {"Doctrine Dark", moves7, 12},
    {"Guile", moves8, 11},
    {"Hokuto", moves9, 15},
    {"Ken Masters", moves10, 11},
    {"Nanase", moves11, 11},
    {"Pullum Purna", moves12, 10},
    {"Ryu", moves13, 12},
    {"Sagat", moves14, 13},
    {"Sharon", moves15, 15},
    {"Skullomania", moves16, 17},
    {"Vega (M. Bison in the West)", moves17, 11},
    {"Vulcano Rosso", moves18, 11},
    {"Zangief", moves19, 11},
    {"Garuda", moves20, 16},
    {"Hayate", moves21, 11},
    {"Kairi", moves22, 12},
    {"Shadow Geist", moves23, 14},
    {"Vega II", moves24, 13},
};
const int g_nComboChars = 25;
