#!/usr/bin/env python3
"""Builds icon_data.c from the PNG files of gui-c/icons (the pictures of the sequence buttons on the Combos tab).
Usage: python gen_icons.py     (needs "pip install pillow"; run it again when a PNG changes)"""
import glob, os
from PIL import Image

here = os.path.dirname(os.path.abspath(__file__))
out = ['/* Generated by gen_icons.py from the PNG files in gui-c/icons. DO NOT EDIT. Straight (not premultiplied) BGRA pixels. */',
       '#include "common.h"', '']
names = []
for path in sorted(glob.glob(os.path.join(here, 'icons', '*.png'))):
    stem = os.path.splitext(os.path.basename(path))[0]
    name = {'tilde': '~', 'plus': '+', 'comma': ','}.get(stem, stem)   # file names cannot hold these signs
    im = Image.open(path).convert('RGBA')
    w, h = im.size
    px = bytearray()
    for r, g, b, a in im.get_flattened_data() if hasattr(im, "get_flattened_data") else im.getdata():
        px += bytes((b, g, r, a))
    out.append('static const unsigned char icon_%s[%d] = {' % (stem, len(px)))
    for i in range(0, len(px), 24):
        out.append('    ' + ','.join(str(v) for v in px[i:i + 24]) + ',')
    out.append('};')
    names.append((name, stem, w, h))
out.append('')
out.append('const IconData g_icons[] = {')
for name, stem, w, h in names:
    out.append('    {"%s", %d, %d, icon_%s},' % (name, w, h, stem))
out.append('};')
out.append('const int g_nIcons = %d;' % len(names))
open(os.path.join(here, 'icon_data.c'), 'w', newline='\n').write('\n'.join(out) + '\n')
print('icons:', len(names))
