/* Tooltips: the explanation of every option, keyed by the option's label text (generated from the old table). */
#include "common.h"

static const struct { const wchar_t *key, *text; } tips[] = {
    {L"Renderer",
     L"The graphics plugin that draws the game.\nOpenGL works on all current Windows versions.\nDirect3D 11 is the launcher's own modern renderer: sharp at any resolution (see Internal resolution).\nIt uses: resolution, rotation, scanlines, filtering (smooth scaling of the finished picture), fullscreen, FPS, frame limiter / skipping and framerate.\nDirect3D is an old DirectX 6 renderer and may not run well on Windows 10/11."},
    {L"Resolution",
     L"Fullscreen resolution (or window size) taken from the modes your display supports.\nModes marked (4:3) show the picture undistorted, like the original arcade monitor."},
    {L"Rotation",
     L"Rotates the picture.\nGame default uses the game's own setting.\n90 / 270 degrees are for vertical (tate) games shown on a turned monitor."},
    {L"Internal resolution",
     L"Direct3D 11 renderer only: how many times the console's own resolution the game is drawn at.\nAuto (the default) picks it from your window / screen size. Higher is sharper but needs a faster graphics card (4x = 4096 x 4096 pixels of video memory work)."},
    {L"Color depth",
     L"Colour precision used in fullscreen.\n32-bit looks best; 16-bit can be faster on very old graphics cards.\nNot used by the Direct3D 11 renderer (it always uses 32-bit)."},
    {L"Scanlines",
     L"Imitates a CRT monitor by drawing a line between picture rows.\nBlack = dark lines, Bright = softer lines."},
    {L"Texture filtering",
     L"Smooths the textures instead of showing blocky pixels.\n0 None: sharp and blocky.\n1 Standard: simple smoothing of 3D surfaces and 2D sprites.\n2 Extended: stronger smoothing, more chance of visible lines.\n3 Standard without sprite smoothing: smooths 3D but keeps 2D sprites sharp.\nFiltering can cause glitches in some games.\nDirect3D 11 renderer: 0 = sharp pixels, 1 - 3 = smooth scaling of the finished picture (no glitches).\nNot used by the Direct3D 11 renderer (its textures are decoded by its own shaders)"},
    {L"Texture quality",
     L"Colour precision of the textures kept in video memory.\n8-bit is the best quality; 4-bit is fastest but looks worst.\nDefault lets the graphics driver decide.\nNot used by the Direct3D 11 renderer."},
    {L"Texture caching",
     L"How the renderer keeps textures in memory (0 - 2).\n2 is the recommended default; try a lower value if textures look wrong.\nNot used by the Direct3D 11 renderer."},
    {L"Color blending",
     L"Enhanced blending of transparent effects.\nOpenGL: 0 = off, 1 = on.  Direct3D: 0 - 2 (more is more accurate).\nNot used by the Direct3D 11 renderer (it has its own blending)."},
    {L"Manual framerate",
     L"Frame rate the limiter aims for (0 - 1000, default 60) when \"Auto-detect framerate\" is off. Greyed out while auto-detect is on."},
    {L"Fullscreen",
     L"Run the game fullscreen at the chosen resolution instead of in a window."},
    {L"Dithering",
     L"Adds a fine pattern that hides colour banding.\nOnly useful in 16-bit colour depth.\nNot used by the Direct3D 11 renderer (it draws without dither); see Dither Smoothing for that renderer."},
    {L"Show FPS",
     L"Shows the frames-per-second counter on the game screen."},
    {L"Frame limiter",
     L"Keeps the game at its normal speed.\nTurn it off to run as fast as the PC allows (the game will be too fast)."},
    {L"Frame skipping",
     L"Skips drawing some frames when the PC is too slow, so the game keeps its speed. Off by default."},
    {L"Auto-detect framerate",
     L"Detects 50 or 60 Hz from the game.\nWhen off, the Manual framerate is used."},
    {L"3D texture smoothing",
     L"Direct3D 11 renderer only.\nSmooths the textures of 3D objects (bilinear) instead of showing blocky texels, e.g. on floors and walls seen up close.\n2D sprites and backgrounds stay sharp.\nOn by default; turn it off if some game has textures with transparent edges that can show faint outlines when smoothed.\n(\"Texture Filtering\" under OpenGL / Direct3D 6 is a different option.)"},
    {L"FXAA filter",
     L"Direct3D 11 renderer only.\nA fast post-process filter that smooths jagged edges over the final picture (also 2D art), at a slight softening."},
    {L"Dither smoothing",
     L"Direct3D 11 renderer only.\nReduces the checkerboard dither pattern that some games bake into their backgrounds and images: a pixel that differs a little from four alike neighbours is blended with them. Low only touches very faint patterns; High also smooths stronger ones (and may soften very fine detail).\nThe renderer itself adds no dither; this only affects patterns in the game's own graphics."},
    {L"Fullscreen mode",
     L"Direct3D 11 renderer only.\nFullscreen: the screen is switched to the Width x Height set in Resolution.\nBorderless: a borderless window covers the screen at its current desktop resolution; the picture is scaled to it. Faster to start and to switch away (Alt+Tab), and no flicker on multi-monitor setups."},
    {L"V-Sync",
     L"Direct3D 11 renderer only.\nShows each frame in step with the screen refresh, which removes tearing. The game keeps its speed (the frame limiter still applies). Can add a little input delay, and uneven motion if the screen refresh is not 50 or 60 Hz."},
    {L"Aspect ratio",
     L"Direct3D 11 renderer only.\nStretch To Window: the picture fills the window (rotated games and a 4:3 fullscreen resolution keep their shape).\n4:3: the original shape, with black bars where the window is wider or taller.\n16:9: the picture is widened to 16:9 (black bars elsewhere).\nPixel Perfect: the picture is a whole number of times the console picture (2x, 3x ...), with square pixels and black bars around it. If the window is smaller than the console picture, it is scaled down to fit."},
    {L"Overscan crop",
     L"Direct3D 11 renderer only.\nCuts the given number of console pixels off every edge of the picture and enlarges the rest to fill the screen. Hides the black or noisy borders some games draw (overscan), like on an arcade monitor."},
    {L"Bezel image (D3D11)",
     L"Direct3D 11 renderer only.\nA PNG picture of a cabinet or monitor frame with a transparent window in the middle. The game is shown in that window and the frame is drawn around it, scaled to fit the window of the game. The transparent window is found automatically (the transparent area through the middle of the image).\nLeave empty for no bezel.\nPer game: a file bezels\\<set name>.png (for example bezels\\sfex2.png) next to ZiNc.exe is used for that game (and for its clones) instead of this bezel."},
    {L"Theme",
     L"The look of the launcher: System follows the Windows app colour mode, Light or Dark.\nThe theme changes after a restart: when you press OK you are asked whether to restart ZiNc EX now. The same choice is in the View menu."},
    {L"When A Game Starts",
     L"What the launcher does when you start a game.\nKeep The Launcher Open: nothing (the default).\nMinimize The Launcher: it is minimized while the game runs and comes back when the game ends.\nClose The Launcher: it closes, the game goes on without it (a trainer started with the game keeps running too). Desktop icons are not affected."},
    {L"Classic Layout",
     L"Ticked: the General, Video, Audio, Controls and Combos tabs are on the right of the game list (the classic layout).\nUnticked: the tabs are in a window of their own, so the game list has the whole main window. Open it with the Settings button, Options > Settings… or F9.\nThe layout changes when you press OK. The same choice is in the View menu."},
    {L"xBRZ filter",
     L"Direct3D 11 renderer only.\nThe xBRZ pixel-art scaler gives clean, smooth edges on diagonals and curves without blurring.\nAll graphics: the whole game is drawn at the console's own resolution and enlarged with xBRZ (Internal resolution is ignored).\n2D objects only: sprites, images, backgrounds and screen-aligned panels get xBRZ, while 3D models stay sharp at the Internal resolution."},
    {L"Enable sound",
     L"Turns the game's sound on or off."},
    {L"Sound filter",
     L"Softens the sound with a low-pass filter. Slightly better quality for a tiny amount of extra CPU."},
    {L"Filter cutoff (Hz)",
     L"Frequency above which the sound filter cuts the sound. Default: 22050."},
    {L"Lite surround",
     L"Widens the stereo image with a simple surround effect."},
    {L"Surround strength",
     L"How strong the lite surround effect is. Default: 40."},
    {L"Stereo exciter",
     L"Widens the stereo image and adds a little sparkle to the sound."},
    {L"ROMs folder",
     L"Folder that holds the game ROM sets (zip files or folders). A relative path starts in the ZiNc folder."},
    {L"Browse…",
     L"Choose the ROMs folder."},
    {L"List Only Available ROMs",
     L"Only show games whose ROM set (and parent / BIOS set) is in the ROMs folder."},
    {L"Slow Geometry",
     L"Uses slower but more accurate geometry calculations.\nTry it if you see broken graphics; some games (for example Gallop Racer 3) need it."},
    {L"Enable Logs",
     L"Writes log files: zinc-d3d11.log (Direct3D 11 renderer) and ZiNc-EX_launch.log (desktop icons).\nOff by default: the launcher and the Direct3D 11 renderer then write no log files. ZiNc itself and other plugins keep their own behaviour."},
    {L"Hide Console",
     L"Starts ZiNc without its black console window.\nApplies to games started from the launcher, not to desktop icons."},
    {L"Use enhanced input (remappable keys, XInput, DirectInput)",
     L"Uses the launcher's own input plugin: remappable keys, game controllers and combo macros.\nWhen off, ZiNc's original keyboard plugin is used."},
    {L"XInput",
     L"Accept Xbox-style controllers (XInput)."},
    {L"DirectInput",
     L"Accept other game controllers and joysticks (DirectInput)."},
    {L"Pad directions from D-pad / stick",
     L"Move with the controller's D-pad, hat or left stick without setting them up; otherwise only the buttons you assign work."},
    {L"Player 1 pad",
     L"Which controller player 1 uses. Auto takes the first one found; None ignores controllers (keyboard only)."},
    {L"Player 2 pad",
     L"Which controller player 2 uses. Auto takes the next one found; None ignores controllers (keyboard only)."},
    {L"Stick threshold %",
     L"How far the analog stick must be pushed (in %) before it counts as a direction."},
    {L"Key…",
     L"Press a keyboard key for the selected action (Esc cancels, Delete unbinds)."},
    {L"XInput…",
     L"Choose the Xbox-controller button for the selected action."},
    {L"DirectInput…",
     L"Choose the joystick button, hat or axis for the selected action."},
    {L"Clear",
     L"Remove the keyboard and controller assignments of the selected action."},
    {L"Defaults",
     L"Reset all actions to the default keys and buttons."},
    {L"Detect",
     L"Look for connected controllers again."},
    {L"Step (ms)",
     L"How long each step of a combo is held, in milliseconds. Lower is faster; default 30."},
    {L"Charge (ms)",
     L"How long \"Hold ... (charge)\" steps hold the direction, in milliseconds. Default 600. The game needs a minimum of charge: if the charge moves (Guile, Blanka, Vega ...) do not come out, raise it."},
    {L"Load character",
     L"Fills the list with all moves of the chosen character (Meteor and Super Combos first)."},
    {L"Character",
     L"Character whose moves are offered in the Move list."},
    {L"Move",
     L"Sets the selected row to this move (name and button sequence)."},
    {L"Combo Defaults",
     L"Puts the Combos tab back to its start values: the default triggers, the Ryu move list and the step / charge times. Other tabs are not changed."},
    {L"Profile",
     L"Named controls layouts (arcade stick, pad, keyboard ...). Pick one to load it into this tab (the pads, the stick threshold and every binding), or press Save As to keep the current layout. A game can use its own profile (Game > Game Settings)."},
    {L"Save As…",
     L"Saves the pads, the stick threshold and all bindings of this tab as a profile."},
    {L"Delete Profile",
     L"Deletes the chosen profile."},
    {L"Restore Defaults",
     L"Restores the video, audio and system settings to their defaults (the same as Options > Default Settings).\nThe Controls and Combos settings, the ROMs folder and the favorites are kept."},
    {L"Reset Filters",
     L"Sets the Region, Maker and Genre filters back to All and puts the game list back in its normal order (by number, ascending). The filters and the order are remembered for the next start."},
    {L"Region Filter",
     L"Shows only the games of one region: US, JP, ASIA or WORLD. The region is read from the words between ( ) in the game's name; a game that does not say is listed as Other."},
    {L"Maker Filter",
     L"Shows only the games of one maker. The maker is guessed from the game's name and BIOS (ZiNc's list does not tell it), so some games are listed as Other."},
    {L"Genre Filter",
     L"Shows only fighting games, shooters, racing games ... The genre is guessed from the game's name, so some games are listed as Other."},
    {L"Trainer Program",
     L"A trainer for ZiNc (for example Zinc 1.1 Trainer.exe) that is started together with the game and closed when the game ends. Choose the program, then tick the box below (or switch it for single games in Game > Game Settings)."},
    {L"Clear ROMs Folder",
     L"Empties the ROMs folder box (after a question)."},
    {L"Clear Trainer Program",
     L"Empties the trainer program box (after a question)."},
    {L"Browse Trainer",
     L"Chooses the trainer program."},
    {L"Start Trainer With Games",
     L"Starts the trainer program together with every game. A single game can differ: Game > Game Settings > Start Trainer."},
    {L"Dark Theme",
     L"A dark look for the launcher (experimental). The theme changes after a restart: when you tick or untick this option you are asked whether to save the settings and restart ZiNc EX now (Yes), or later (No). If you choose No, press OK and start ZiNc EX again yourself."},
    {L"Plays For",
     L"Which player's controls the combo presses: Player 1 or Player 2."},
    {L"Player Side",
     L"The side of the screen your character stands on.\nLeft (default): the character is on the left and looks right: Forward = Right, Back = Left.\nRight: the character is on the right and looks left: Forward = Left, Back = Right.\nIt only mirrors the directions of the move (a fireball goes the right way). It is fixed for the row: the plugin cannot tell if you switch sides during a match."},
    {L"Sequence",
     L"The moves the row plays, for example \"Quarter-circle Forward + Heavy Punch\" or \"D, DR, R + Heavy Punch\" (D = Down, DR = Down-Right, R = Right, U = Up, L = Left, ...). Choosing a move fills it in; you can also type your own. See the notes above."},
};

const wchar_t *tip_for(const wchar_t *label) {
    size_t i;
    for (i = 0; i < sizeof tips / sizeof tips[0]; i++)
        if (_wcsicmp(tips[i].key, label) == 0) return tips[i].text;   /* labels are matched without regard to case */
    return NULL;
}
